export const products = [
  

  {
    title: "Acabou o Chorare",
    category: 2,
    price: 66.0,
    img: "./src/assets/img/2.jpg",
    band: "Novos Baianos",
    year: 1972,
    id: 1,
  },
  {
    title: "Nirvana Discografia",
    category: 8,
    price: 50.0,
    img: "./src/assets/img/3.jpg",
    band: "Nirvava",
    year: 1990,
    id: 2,
  },
  {
    title: "Both Sides",
    category: 1,
    price: 22.0,
    img: "./src/assets/img/4.jpg",
    band: "Phil Collins",
    year: 1993,
    id: 3,
  },
  {
    title: "Led Zeppelin",
    category: 8,
    price: 89.0,
    img: "./src/assets/img/5.jpg",
    band: "Led Zeppelin",
    year: 1971,
    id: 4,
  },
  {
    title: "Black Sabbath",
    category: 8,
    price: 99.0,
    img: "./src/assets/img/6.jpg",
    band: "Black Sabbath",
    year: 1970,
    id: 5,
  },
  {
    title: "Guns N' Roses",
    category: 8,
    price: 120.0,
    img: "./src/assets/img/7.jpg",
    band: "Guns N' Roses",
    year: 1987,
    id: 6,
  },
  {
    title: "24K Magic",
    category: 1,
    price: 89.0,
    img: "./src/assets/img/8.jpg",
    band: "Bruno Mars",
    year: 2016,
    id: 7,
  },
  {
    title: "Unorthodox Jukebox",
    category: 1,
    price: 99.0,
    img: "./src/assets/img/9.jpg",
    band: "Bruno Mars",
    year: 2012,
    id: 8,
  },
  {
    title: "Doo-Wops & Hooligans",
    category: 1,
    price: 120.0,
    img: "./src/assets/img/10.jpg",
    band: "Bruno Mars",
    year: 2010,
    id: 9,
  },
  {
    title: "Clube da Esquina",
    category: 2,
    price: 89.0,
    img: "./src/assets/img/11.jpg",
    band: "Milton Nascimento",
    year: 1972,
    id: 10,
  },
  {
    title: "Elis & Tom",
    category: 2,
    price: 99.0,
    img: "./src/assets/img/12.jpg",
    band: "Elis Regina, Tom Jobim",
    year: 1974,
    id: 11,
  },
  {
    title: "Álibi",
    category: 2,
    price: 120.0,
    img: "./src/assets/img/13.jpg",
    band: "Maria Bethânia",
    year: 1978,
    id: 12,
  },
  {
    title: "Pé de Serra",
    category: 3,
    price: 199.99,
    img: "./src/assets/img/14.jpg",
    band: "Luiz Gonzaga",
    year: 1952,
    id: 13,
  },
  {
    title: "Forró do Xenhenhém",
    category: 3,
    price: 289.0,
    img: "./src/assets/img/15.jpg",
    band: "Alceu Valença",
    year: 1984,
    id: 14,
  },
  {
    title: "São João na Roça",
    category: 3,
    price: 149.5,
    img: "./src/assets/img/16.jpg",
    band: "Dominguinhos",
    year: 2000,
    id: 15,
  },
  {
    title: "Cartola",
    category: 4,
    price: 279.99,
    img: "./src/assets/img/17.jpg",
    band: "Cartola",
    year: 1974,
    id: 16,
  },
  {
    title: "Acústico MTV",
    category: 4,
    price: 189.0,
    img: "./src/assets/img/18.jpg",
    band: "Zeca Pagodinho",
    year: 2003,
    id: 17,
  },
  {
    title: "Meu Lado Samba",
    category: 4,
    price: 219.5,
    img: "./src/assets/img/19.jpg",
    band: "Martinho da Vila",
    year: 1983,
    id: 18,
  },
  {
    title: "Eu Vou Pro Maracatu",
    category: 5,
    price: 419.99,
    img: "./src/assets/img/20.jpg",
    band: "Jackson do Pandeiro",
    year: 1959,
    id: 19,
  },
  {
    title: "De Mala e Cuia",
    category: 5,
    price: 349.0,
    img: "./src/assets/img/21.jpg",
    band: "Dominguinhos",
    year: 1984,
    id: 20,
  },
  {
    title: "O Rei do Baião",
    category: 5,
    price: 189.5,
    img: "./src/assets/img/22.jpg",
    band: "Luiz Gonzaga",
    year: 1984,
    id: 21,
  },
];

export const categories = [
  "Todos",
  "Pop",
  "MPB",
  "Forró",
  "Samba",
  "Baião",
  "Rap",
  "Hip-Hop",
  "Rock",
  "Reggae",
  "Country",
  "Gospel",
];
